
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: daily_guidance_api_development
  <<: *default
  database: daily_guidance_api_test
production:
  adapter: postgresql
  database: db/production
  